### ISSUE TITLE
rk3588 跑模型出现core dump

### ISSUE THREAD

**Issue by KONGDejing** [pengyixing/RK3588-Development-Board#6]
为啥我这边跑模型会出现core dump
![image](https://user-images.githubusercontent.com/45683788/190053960-caa59c39-b246-4c06-8612-3df878df8340.png)

rknn_inputs_set的设置也是按照sample设置的
![image](https://user-images.githubusercontent.com/45683788/190054310-feb6ceaf-56c5-4119-a6d6-57ae453e6d20.png)

**Comment by pengyixing** [comment]
你编译过了跑不起来吗？
